### ISSUE TITLE
It does not seem to work with Tensorflow 2.0

### ISSUE THREAD

**Issue by VladC12** [keithito/tacotron#309]
AttributeError: module 'tensorflow' has no attribute 'contrib'
Found this concerning the issue: https://stackoverflow.com/questions/55870127/module-tensorflow-has-no-attribute-contrib

**Comment by al-faiyad** [comment]
downgrade to version 1.5.1 
However, it won't work in google colab
